name: Deploy model

on:
  repository_dispatch:
    types: [model-trained]
  push:
    branches:
      - master
    paths:
      - '.github/workflows/deploy_model.yml'
      - '.cloud/.azure/deploy_aci.json'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      MODEL_NAME: "porto_seguro_safe_driver_model"
      MODEL_VERSION: "6"
      SERVICE_NAME: "service-aci-mlops-ci"
    steps:
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@v2


      - name: Connect Azure Machine Learning Workspace
        id: aml_workspace
        uses: Azure/aml-workspace@v1
        with:
            azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}


      - name: Deploy Model to ACI
        id: deploy_aci
        uses: Azure/aml-deploy@v1
        with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          model_name:  "${{ env.MODEL_NAME }}"
          model_version: "${{ env.MODEL_VERSION }}"
          parameters_file: "deploy_aci.json"


      - name: Display Aci Deploy Details
        run: |
          echo scoring-endpoint: ${{ steps.deploy_aci.outputs.service_scoring_uri}}
          echo swagger-uri: ${{ steps.deploy_aci.outputs.service_swagger_uri}}


      - name: Smoke Test ACI
        run: |
          python code/util/smoke_test_webservice.py --type ACI --service "${{ env.SERVICE_NAME }}"
