# Register a dataset on Azure Machine Learning
name: Register Dataset
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/register_dataset.yml'
      - 'code/data/*'
      - 'data/*'
jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check Out Repository
      id: checkout_repository
      uses: actions/checkout@v2


    # Setup Python
    - name: Setup Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'


    # Connect or Create the Azure Machine Learning Workspace
    - name: Connect Azure Machine Learning Workspace
      id: aml_workspace
      uses: Azure/aml-workspace@v1
      with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          parameters_file: "workspace.json"

    # Install Python dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi


    # Run register_data.py
    - name: Register Dataset
      run: python code/data/register_data.py