# Register a dataset on Azure Machine Learning
name: Register Dataset
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/register_dataset.yml'
      - 'code/data/*'
      - 'data/*'
jobs:
  register:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repository
      id: checkout_repository
      uses: actions/checkout@v2


    - name: Setup Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'


    - name: Connect Azure Machine Learning Workspace
      id: aml_workspace
      uses: Azure/aml-workspace@v1
      with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          parameters_file: "workspace.json"

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi


    # Run register_data.py
    - name: Register Dataset
      run: python code/data/register_data.py


    - name: Dispatch Repository Event dataset-registered
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.PATTOKEN }}
        event-type: dataset-registered
        client-payload: '{}'